### ISSUE TITLE
Is it possible to switch patch releases of openjdk

### ISSUE THREAD

**Issue by shawnzhu** [michaelklishin/jdk_switcher#16]
The scenario is it needs to lock down the patch release of openjdk like v1.8.0_151 instead of keep using the latest?

E.g., the current openjdk verison from ubuntu xenial is v1.8.0_162 but a travis build environment requires v1.8.0_151.

**Comment by michaelklishin** [comment]
This project [does not enforce versions](https://github.com/michaelklishin/jdk_switcher/blob/master/jdk_switcher.sh), it just switches between what's already available.
